### ISSUE TITLE
Add flux chart diagram for SIR, SEIR and SEIRD models

### ISSUE THREAD

**Issue by marthendalnunes** [neo-empresarial/epidemiological-analysis#2]
Add flux charts like [this](https://miro.medium.com/max/1400/1*B-HZLpVWEgAZ3iloHBJjCA.png) on the lab_notebook for each model.

**Comment by markusbkoch** [comment]
As a reference, page 4 of this PDF shows the kind of stock and flow diagrams we use at BlockScience https://github.com/BlockScience/artonomous/blob/089b1f1af84b5811cf13ebef25763492a7119aa1/token_engineering/Artonomous.pdf

**Comment by markusbkoch** [comment]
Another, more recent example https://github.com/BlockScience/Community_Inclusion_Currencies/blob/master/Colab/CIC_Network_cadCAD_model.ipynb

**Comment by marthendalnunes** [comment]
The stock and flow diagrams can be found here: https://drive.google.com/file/d/1uyRA75Ahue2mzNLtOPOQOHRXkUh0z-83/view?usp=sharing.
